# Generated by Django 4.2.9 on 2024-01-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="property_management.property",
            ),
        ),
    ]
