# Generated by Django 4.2.9 on 2024-01-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property_management", "0002_alter_unit_property"),
        ("tenant_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantassignment",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="property_management.unit",
            ),
        ),
    ]
