# Generated by Django 4.2.9 on 2024-01-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_management", "0002_alter_tenantassignment_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="tenant_management.tenant",
            ),
        ),
    ]
